package:
  name: macs2
  version: 2.1.2

source:
  url: https://files.pythonhosted.org/packages/5e/32/0108a85d9a91c18413e8492bea631725cdbc20b45970ef63e8d0020ef2da/MACS2-2.1.2.1.tar.gz
  sha256: 6ee9381bda61bacf65e2e31bde267cbcd61a1304457f8a00a0eb7632dd12419b

build:
  number: 0
  skip: True  # [py3k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
  run:
    - python
    - numpy
    - r-base

test:
  commands:
    - macs2 --version 2>&1 > /dev/null

about:
  home: https://github.com/taoliu/MACS/
  license: BSD New
  summary: MACS -- Model-based Analysis of ChIP-Seq
