{% set version = "0.3.1.3" %}
{% set sha256 = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855" %}

package:
  name: rnftools
  version: {{ version }}

source:
  url: https://github.com/karel-brinda/rnftools/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: True # [py27]
  script:

requirements:
  host:
    - python
    - pysam
    - snakemake
    - argparse
  run:
    - python
    - samtools
    - pysam
    - wgsim
    - dwgsim
    - art
    - mason
    - curesim
    - snakemake
    - argparse
    - pyfaidx
    - bwa
    - gnuplot >=5.0
    - beautifulsoup4
    - reportlab ==3.3.0

test:
  commands:
    - rnftools -h
  imports:
    - rnftools

about:
  home: http://karel-brinda.github.io/rnftools
  license: MIT
  summary: 'RNF framework for NGS: simulation of reads, evaluation of mappers, conversion of RNF-compliant data.'

