{% set version = '1.0.8' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-knitcitations
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/knitcitations_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/knitcitations/knitcitations_{{ version }}.tar.gz
  sha256: 3b366d6b7cd02998d451f820a7883e6c5c315391a5301112a80c8b725969081e

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, knitr (>= 1.6)
requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-refmanager >=0.8.2
    - r-digest
    - r-httr >=0.3

  run:
    - r-base
    - r-refmanager >=0.8.2
    - r-digest
    - r-httr >=0.3

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('knitcitations')"           # [not win]
    - "\"%R%\" -e \"library('knitcitations')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/cboettig/knitcitations
  license: MIT + file LICENSE
  summary: Provides the ability to create dynamic citations in which the bibliographic information
    is pulled from the web rather than having to be entered into a local database such
    as 'bibtex' ahead of time. The package is primarily aimed at authoring in the R
    'markdown' format, and can provide outputs for web-based authoring such as linked
    text for inline citations.  Cite using a 'DOI', URL, or 'bibtex' file key.  See
    the package URL for details.
  license_family: MIT

# The original CRAN metadata for this package was:

# Package: knitcitations
# Type: Package
# Title: Citations for 'Knitr' Markdown Files
# Authors@R: person("Carl", "Boettiger", role=c("aut", "cre"), email="cboettig@gmail.com")
# Version: 1.0.8
# Description: Provides the ability to create dynamic citations in which the bibliographic information is pulled from the web rather than having to be entered into a local database such as 'bibtex' ahead of time. The package is primarily aimed at authoring in the R 'markdown' format, and can provide outputs for web-based authoring such as linked text for inline citations.  Cite using a 'DOI', URL, or 'bibtex' file key.  See the package URL for details.
# URL: https://github.com/cboettig/knitcitations
# BugReports: https://github.com/cboettig/knitcitations/issues
# License: MIT + file LICENSE
# VignetteBuilder: knitr
# Depends: R (>= 3.0)
# Imports: RefManageR (>= 0.8.2), digest, httr (>= 0.3), methods, utils
# Suggests: testthat, knitr (>= 1.6)
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-07-03 10:47:55 UTC; rstudio
# Author: Carl Boettiger [aut, cre]
# Maintainer: Carl Boettiger <cboettig@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-07-04 06:09:31 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
